version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.2.6-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - -m
      - models
      - --enable-api
      - --cors
      - "*"
  app:
    image: adp2000/prova_rasa:esercizioE31
    ports:
      - 5055:5055
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: adp2000
      MONGO_INITDB_ROOT_PASSWORD: provamongo
  apache:
    image: httpd:latest
    container_name: my-apache-appE31
    ports:
    - '8080:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs